export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const ADD_CURRENT_USER = 'ADD_CURRENT_USER';
export const ADD_SERVICE_WORKERS = 'ADD_SERVICE_WORKERS';
export const ADD_TIP = 'ADD_TIP';